### PR TITLE
Produce at most N threshold reached messages when {Threshold} * N messages are received

### PR DESCRIPTION
**Pull request by bbrandt**
This introduces a change in behavior in commit 5802dd47c2e6b738fd1e575352e3531e93eac3b2. 

## Previous behavior: "Reset on threshold reached"=false:
When threshold is reached, all messages exceeding the threshold will log a threshold reached message until the count is reduced by the passing of time.  Given a constant stream of log messages at a high enough rate, every message will produce a threshold reached message.

## New behavior: "Reset on threshold reached"=true:
When threshold is reached, after a threshold reach message is logged, the counters will be reset.  Threshold must be reached again before another threshold reached message is logged. Given a threshold of N, a threshold reached message will be logged at most every N messages.

## Other changes: 
* Added tests around ThresholdReactor to document its behavior in 48594ee9c3f4d0b1b4b73852a7ab852fcb2fa459 and 69a13dbdf76c9838f4e6f1d5aec86cd60319e0f7
* Reduced some duplication in ThresholdReactor in 09c91c5e360104b27a509d840aa462203c7a63eb

### CODE REVIEW

**Comment by nblumhardt** [comment]
Hi Ben, thanks for the PR! The refactor looks great.

Is the scenario you're addressing here covered by the `SuppressionTimeSeconds` setting? If set, additional "threshold reached" messages shouldn't be raised until the specified number of seconds elapses.

**Comment by bbrandt** [comment]
I have below a couple of the requirements for notifications I am looking at implementing.  For the first, suppression works great.  For the second requirement, I cannot devise a good way for the Threshold App to meet the requirement in its current state.

## Req 1
#### When {criteria} occurs. Alert at most once per {number} minutes.
Suppression time works great for this one.  The plan is to 
* Create a signal with the specified criteria 
* feeding an app instance of Threshold Detection 
  * with detection window of 2, 
  * threshold of 1, 
  * threshold name of {threshold}, 
  * and suppression time of {number}.  
* Create a signal to capture events tagged with {threshold}.

## Req 2
#### When {criteria} occurs {number occurrences} within {number minutes} minutes.
I've mapped this to Seq constructs as:
* Create a signal with the specified criteria 
* feeding an app instance of Threshold Detection 
  * with detection window of {number minutes}, 
  * threshold of {number occurrences}, 
  * and threshold name of {threshold}.  
* Create a signal to capture events tagged with {threshold}.

### Example Case 1
* When {criteria} occurs {number occurrences} within {number minutes} minutes.
* Receiving 1 matching logs per minute.  
* Threshold set to 20. 
* Sliding windows set to 60 minutes.
I  would expect in this case to receive 2 or 3 notifications in an hour.  With the previous Threshold behavior, without suppression, after the initial 20 matching logs, I would receive a steady stream of 1 per minute threshold notifications.  

For this specific case, as a workaround, I could set a suppression time of 20 seconds.  But this would be problematic if the log velocity increased.

### Example Case 2
* When {criteria} occurs {number occurrences} within {number minutes} minutes.
* Receiving 4 matching logs per minute.  
* Threshold set to 20. 
* Sliding windows set to 60 minutes.
* Suppression time of 20 seconds. 
I would expect to receive ~15 notifications based on the requirement 2.  Instead I will receive 2 or 3.

## Followup Question
Is it possible that anyone would consider the previous behavior (notifying for every message after the threshold is reached) desirable?

**Comment by nblumhardt** [comment]
Thanks for the detailed reply Ben. I think your change is probably broadly desirable. The existing behaviour might possibly work well for long-window/short-threshold configurations, I have no idea if anyone relies on it though.

What do you think about a checkbox "Reset on threshold reached?" - defaulting to false would preserve the current behaviour, selecting it would behave as in this PR?

Regards,
Nick

**Comment by bbrandt** [comment]
I'm fine with having an option if that's what we need to do.  I am unable to think of a useful business case for the previous behavior, so I'll leave that decision up to you.

**Comment by nblumhardt** [comment]
Hi Ben - I am not certain how much it is used, but I think the long-window scenario is still relevant (think of the additional messages, after the suppression time, as indicating "hey, this condition is still occurring!"). Resetting in these cases would delay feedback on whether a threshold was still exceeded.

If the checkbox approach works for you I think it's a good option here, at least to stay on the safe side.

**Comment by bbrandt** [comment]
Hi Nick,
I was looking at adding the "Reset on threshold reached" option to Seq.App.Thresholds, but I noticed some of my tests are occasionally failing.  An out of range exception occurs when the eventSeconds  in TrySlideWindow() in ThresholdReactor is 1 second before the _currentBucketSecond in ThresholdReactor.  Is this something that could occur in normal operation or do I just need to adjust my test?

I see that  currentBucketSecond is set in the OnAttached() of ThresholdReactor, but I am unsure of where the TimestampUtc of the Seq.Apps.Event<LogEventData> originates.
Thanks.

**Comment by bbrandt** [comment]
I updated the test in this pull request to not have the error condition.  If event time can be before the app attached time, possibly in the case of running for older events, then this other branch still has the error condition and a possible workaround:
https://github.com/continuousit/seq-apps/compare/master...bbrandt:event-time-before-bucket-seconds?expand=1

**Comment by nblumhardt** [comment]
Hi Ben, thanks for the information regarding the error condition, this is very interesting. It's been a while since I dug deeply into this part of the code - investigating now :+1:

**Comment by nblumhardt** [comment]
Thanks for the PR Ben. I think I have the error pinned down - in the constructor of `ThresholdReactor` we initialize `_currentBucketSeconds` to an un-rounded seconds value, which will make a mess of quite a bit of logic. Pushing that change through now. Cheers!

**Comment by bbrandt** [comment]
Thanks for looking into this Nick.

**Comment by nblumhardt** [comment]
@bbrandt just a heads up, I'm creating a new (public) CI build for this project, so it may take a day or two for me to get the new package version published.

**Comment by bbrandt** [comment]
Thanks for the heads up.

**Comment by nblumhardt** [comment]
This is published now.

**Pull request merged**
